/*
 * AmiMe — Charm Catalogue
 * -----------------------------------------------------------------------------
 * Every charm identified from the five product sheets in /charms.
 *
 * Each entry:
 *   id       unique slug (stable — use as the Shopify product handle / SKU key)
 *   name     human-readable charm name
 *   emoji    quick visual stand-in for the POC UI
 *   sheet    which source photo it lives on (1-5) — see SHEETS below
 *   pos      "row,col" position on that sheet (for finding it on the photo)
 *   category one of: flora, fruit, animal, sea, home, love, word, celestial,
 *            object, folk, music, luck, family, mama
 *   meaning  the story / sentiment the charm tends to carry
 *   tags     concept words used by the matcher (objects + emotions + occasions)
 *
 * The `tags` are deliberately broad — they mix the literal subject with the
 * feelings, occasions and themes a customer might describe in a sentence.
 * This is what lets "a summer by the sea where we fell in love" surface the
 * shell, the lemon and the heart.
 */
(function (root) {
  "use strict";

  var SHEETS = {
    1: { file: "charms/sheet-1-blue-white.jpeg", name: "Blue & White Riviera" },
    2: { file: "charms/sheet-2-dolce-vita.jpeg", name: "La Dolce Vita" },
    3: { file: "charms/sheet-3-mama.jpeg", name: "Mama & Family" },
    4: { file: "charms/sheet-4-folk-oval.jpeg", name: "Hand-Painted Folk" },
    5: { file: "charms/sheet-5-terracotta.jpeg", name: "Terracotta & Treasures" }
  };

  var CHARMS = [
    /* ---- Sheet 1 — Blue & White Riviera ------------------------------- */
    { id: "blue-daisy-tile", name: "Blue Daisy Tile", emoji: "💠", sheet: 1, pos: "1,1",
      category: "flora", meaning: "fresh starts, simple joy, springtime",
      tags: ["flower","daisy","blue","spring","bloom","fresh","new beginning","simple","joy","garden","delft"] },
    { id: "olive-branch", name: "Olive Branch", emoji: "🫒", sheet: 1, pos: "1,2",
      category: "flora", meaning: "peace, abundance, the Mediterranean",
      tags: ["olive","olives","peace","mediterranean","greece","italy","abundance","calm","harvest","green","reconcile","truce"] },
    { id: "joie-flowers", name: "\"Joie\" Floral Oval", emoji: "🌸", sheet: 1, pos: "1,3",
      category: "word", meaning: "joy — said out loud",
      tags: ["joy","joie","happy","happiness","delight","cheer","french","celebrate","bliss","flower"] },
    { id: "blue-perfume", name: "Blue Perfume Bottle", emoji: "🧴", sheet: 1, pos: "1,4",
      category: "object", meaning: "beauty, self-care, a signature scent",
      tags: ["perfume","scent","fragrance","beauty","elegance","self care","glamour","vanity","bottle","luxury"] },
    { id: "clover-sprig-navy", name: "Clover Sprig", emoji: "🍀", sheet: 1, pos: "1,5",
      category: "luck", meaning: "luck and quiet hope",
      tags: ["clover","luck","lucky","hope","four leaf","irish","fortune","charm","nature","sprig"] },
    { id: "flower-pot-red", name: "Red Bloom Pot", emoji: "🪴", sheet: 1, pos: "1,6",
      category: "flora", meaning: "home, nurturing, watching things grow",
      tags: ["flower pot","plant","grow","growth","home","nurture","garden","bloom","red","care","gardening"] },
    { id: "blue-spoon", name: "Blue Spoon", emoji: "🥄", sheet: 1, pos: "2,1",
      category: "object", meaning: "cooking, nourishment, the kitchen table",
      tags: ["spoon","cook","cooking","kitchen","food","nourish","baking","chef","recipe","home","comfort"] },
    { id: "floral-boot", name: "Floral Boot", emoji: "👢", sheet: 1, pos: "2,2",
      category: "object", meaning: "wandering, independence, a free spirit",
      tags: ["boot","cowboy","cowgirl","western","adventure","travel","independence","free spirit","walk","journey","ranch"] },
    { id: "coral-heart", name: "Coral Heart", emoji: "🪸", sheet: 1, pos: "2,3",
      category: "sea", meaning: "love that grows from the sea",
      tags: ["coral","heart","ocean","sea","love","reef","blue","nature","diving","summer"] },
    { id: "white-quilted-heart", name: "Quilted White Heart", emoji: "🤍", sheet: 1, pos: "2,4",
      category: "love", meaning: "pure, tender love",
      tags: ["heart","love","pure","tender","white","sweet","affection","gentle","devotion"] },
    { id: "joie-de-vivre", name: "\"Joie de Vivre\" Tile", emoji: "✨", sheet: 1, pos: "2,5",
      category: "word", meaning: "the sheer joy of being alive",
      tags: ["joie de vivre","joy of living","zest","alive","happy","french","celebrate","life","vivacious","spirit"] },
    { id: "scallop-shell", name: "Scallop Shell", emoji: "🐚", sheet: 1, pos: "2,6",
      category: "sea", meaning: "the seaside, summer, setting sail",
      tags: ["shell","scallop","beach","ocean","sea","summer","coast","venus","sail","mermaid","holiday","seaside"] },
    { id: "blue-flower-square-2", name: "Cornflower Tile", emoji: "🌼", sheet: 1, pos: "3,1",
      category: "flora", meaning: "a small blue flower, steadfast",
      tags: ["flower","cornflower","blue","bloom","field","wildflower","spring","steadfast","delft"] },
    { id: "blue-knot", name: "Love Knot", emoji: "🎗️", sheet: 1, pos: "3,2",
      category: "love", meaning: "an unbreakable tie between people",
      tags: ["knot","tie","bond","connection","together","forever","love","friendship","link","blue"] },
    { id: "blue-flower-emblem", name: "Blue Flower Emblem", emoji: "🏵️", sheet: 1, pos: "3,3",
      category: "flora", meaning: "a keepsake bloom",
      tags: ["flower","emblem","blue","bloom","keepsake","garden","vintage","delft"] },
    { id: "love-letter-envelope", name: "Love-Letter Envelope", emoji: "💌", sheet: 1, pos: "3,4",
      category: "love", meaning: "a heartfelt message sent with love",
      tags: ["envelope","letter","love letter","message","mail","romance","words","note","long distance","heart","write"] },
    { id: "crescent-moon", name: "Crescent Moon", emoji: "🌙", sheet: 1, pos: "3,5",
      category: "celestial", meaning: "dreams, night, quiet wonder",
      tags: ["moon","crescent","night","dream","sleep","luna","calm","wonder","stars","mystic","celestial"] },
    { id: "sprig-heart", name: "Sprig Heart", emoji: "💚", sheet: 1, pos: "3,6",
      category: "love", meaning: "love rooted in nature",
      tags: ["heart","sprig","flower","love","nature","growth","tender","blue"] },

    /* ---- Sheet 2 — La Dolce Vita -------------------------------------- */
    { id: "teal-house", name: "Teal Cottage", emoji: "🏠", sheet: 2, pos: "1,1",
      category: "home", meaning: "home, belonging, a place that's yours",
      tags: ["house","home","cottage","belonging","family","cozy","new home","move","first home","village"] },
    { id: "pink-heart-house", name: "Pink Heart House", emoji: "🏡", sheet: 2, pos: "1,2",
      category: "home", meaning: "a home full of love",
      tags: ["house","home","love","heart","family","cozy","warm","first home","newlywed"] },
    { id: "red-roof-house", name: "Red-Roof House", emoji: "🏘️", sheet: 2, pos: "1,3",
      category: "home", meaning: "family roots and warm windows",
      tags: ["house","home","family","roots","village","cozy","childhood","hometown"] },
    { id: "blue-house", name: "Blue Townhouse", emoji: "🏠", sheet: 2, pos: "1,4",
      category: "home", meaning: "a new chapter at a new address",
      tags: ["house","home","townhouse","new home","move","city","belonging","chapter"] },
    { id: "church-steeple", name: "Church Steeple", emoji: "⛪", sheet: 2, pos: "1,5",
      category: "home", meaning: "faith, ceremony, the old town square",
      tags: ["church","faith","wedding","ceremony","town","europe","travel","steeple","tradition","baptism","spiritual"] },
    { id: "cherry-cluster-oval", name: "Cherry Cluster", emoji: "🍒", sheet: 2, pos: "2,1",
      category: "fruit", meaning: "sweetness and a pair that belongs together",
      tags: ["cherry","cherries","fruit","sweet","summer","pair","couple","red","orchard","dessert"] },
    { id: "gingham-flower-pot", name: "Gingham Flower Box", emoji: "🪟", sheet: 2, pos: "2,2",
      category: "flora", meaning: "a sunny windowsill garden",
      tags: ["flowers","window box","garden","gingham","home","spring","bloom","cottage","cheerful"] },
    { id: "forget-me-not-hex", name: "Forget-Me-Not Hexagon", emoji: "💙", sheet: 2, pos: "2,3",
      category: "flora", meaning: "remembrance — don't forget me",
      tags: ["forget me not","flower","remember","memory","blue","loyalty","keepsake","missing you","devotion"] },
    { id: "poppy-stripe-oval", name: "Red Poppies", emoji: "🌺", sheet: 2, pos: "2,4",
      category: "flora", meaning: "remembrance and bold beauty",
      tags: ["poppy","poppies","flower","red","remember","bold","field","summer","beauty"] },
    { id: "blue-bow-oval", name: "Blue Bow", emoji: "🎀", sheet: 2, pos: "2,5",
      category: "object", meaning: "a gift, a girlish wink, something tied with care",
      tags: ["bow","ribbon","gift","present","coquette","feminine","pretty","tied","sweet","blue"] },
    { id: "ginger-jar", name: "Blue Ginger Jar", emoji: "🏺", sheet: 2, pos: "3,1",
      category: "object", meaning: "heirlooms, collecting, timeless taste",
      tags: ["vase","ginger jar","chinoiserie","heirloom","antique","home decor","elegance","collector","blue","timeless"] },
    { id: "lemon-oval", name: "Amalfi Lemons", emoji: "🍋", sheet: 2, pos: "3,2",
      category: "fruit", meaning: "Italian summers, zest, sunshine",
      tags: ["lemon","lemons","citrus","amalfi","italy","summer","zest","sunshine","mediterranean","fresh","sour"] },
    { id: "grapes-oval", name: "Purple Grapes", emoji: "🍇", sheet: 2, pos: "3,3",
      category: "fruit", meaning: "the harvest, wine, good company",
      tags: ["grapes","wine","vineyard","harvest","abundance","autumn","feast","purple","tuscany","celebrate"] },
    { id: "blue-flower-mini", name: "Little Blue Bloom", emoji: "🌸", sheet: 2, pos: "3,4",
      category: "flora", meaning: "a small everyday flower",
      tags: ["flower","blue","small","bloom","everyday","simple","garden"] },
    { id: "la-dolce-vita", name: "\"La Dolce Vita\" Tile", emoji: "🍸", sheet: 2, pos: "4,1",
      category: "word", meaning: "the sweet life",
      tags: ["la dolce vita","sweet life","italy","joy","celebrate","good life","leisure","happy","living"] },
    { id: "violet-pot-square", name: "Violet Flower Pot", emoji: "🌷", sheet: 2, pos: "4,2",
      category: "flora", meaning: "a tended garden, patience rewarded",
      tags: ["flower pot","violet","plant","garden","grow","home","spring","nurture","bloom"] },
    { id: "tulip-gold-round", name: "Golden Tulip", emoji: "🌷", sheet: 2, pos: "4,3",
      category: "flora", meaning: "spring, elegance, perfect love",
      tags: ["tulip","flower","spring","elegant","love","holland","bloom","gold","graceful"] },
    { id: "pink-bow-oval", name: "Pink Bow", emoji: "🎀", sheet: 2, pos: "4,4",
      category: "object", meaning: "soft, romantic, beautifully wrapped",
      tags: ["bow","ribbon","pink","coquette","feminine","gift","romance","pretty","sweet"] },

    /* ---- Sheet 3 — Mama & Family -------------------------------------- */
    { id: "always-connected-hands", name: "\"Always Connected\" Hands", emoji: "🤝", sheet: 3, pos: "1,1",
      category: "family", meaning: "the unbreakable link between two people",
      tags: ["hands","connection","bond","together","family","love","mother","child","pinky promise","always","support","holding hands"] },
    { id: "family-sweetness", name: "\"Family Sweetness\"", emoji: "🍓", sheet: 3, pos: "1,2",
      category: "family", meaning: "the sweetness of family life",
      tags: ["family","sweet","strawberry","gingham","home","togetherness","love","warmth","kin"] },
    { id: "mama-stars", name: "\"Mama\" Starry Medallion", emoji: "⭐", sheet: 3, pos: "1,3",
      category: "mama", meaning: "for Mama, under the stars",
      tags: ["mama","mom","mother","mum","parent","mothers day","love","stars","family"] },
    { id: "lavender-soothing", name: "\"Soothing Presence\" Lavender", emoji: "💜", sheet: 3, pos: "1,4",
      category: "flora", meaning: "calm, comfort, a soothing presence",
      tags: ["lavender","calm","soothe","comfort","peace","relax","gentle","presence","healing","purple","serenity","grandmother"] },
    { id: "shamrock-check", name: "Shamrock Check", emoji: "☘️", sheet: 3, pos: "2,1",
      category: "luck", meaning: "luck of the Irish",
      tags: ["shamrock","clover","luck","lucky","irish","ireland","fortune","green","st patricks"] },
    { id: "blue-sardine", name: "Blue Sardine", emoji: "🐟", sheet: 3, pos: "2,2",
      category: "sea", meaning: "the sea, Portugal, a catch worth keeping",
      tags: ["fish","sardine","sea","ocean","portugal","pisces","catch","blue","fishing","coast"] },
    { id: "safe-harbor-nest", name: "\"Safe Harbor\" Nest", emoji: "🪺", sheet: 3, pos: "2,3",
      category: "family", meaning: "safety, home, new life",
      tags: ["nest","eggs","safe","harbor","home","protect","mother","new baby","beginning","family","shelter","nurture"] },
    { id: "heart-stars-round", name: "Starry Heart", emoji: "❤️", sheet: 3, pos: "2,4",
      category: "love", meaning: "love that shines",
      tags: ["heart","love","stars","red","romance","adore","valentine","shine"] },
    { id: "super-mama", name: "\"Super Mama\"", emoji: "🦸", sheet: 3, pos: "2,5",
      category: "mama", meaning: "the everyday hero — Mom",
      tags: ["mama","mom","mother","super","hero","strong","mothers day","powerful","amazing"] },
    { id: "mama-hearts", name: "\"Ma'ma\" Hearts", emoji: "💗", sheet: 3, pos: "3,1",
      category: "mama", meaning: "love for Mom",
      tags: ["mama","mom","mother","mum","love","hearts","mothers day","family"] },
    { id: "love-script", name: "\"Love\" Script", emoji: "❤️", sheet: 3, pos: "3,2",
      category: "word", meaning: "love, simply",
      tags: ["love","romance","adore","valentine","heart","sweetheart","affection","words"] },
    { id: "hearts-letter", name: "\"Heart's Letter\" Envelope", emoji: "💌", sheet: 3, pos: "3,3",
      category: "love", meaning: "a letter sealed with the heart",
      tags: ["envelope","letter","love letter","heart","message","romance","rose","mail","words","long distance","write"] },
    { id: "black-bow-round", name: "Black Bow", emoji: "🎀", sheet: 3, pos: "3,4",
      category: "object", meaning: "chic, polished, a little dramatic",
      tags: ["bow","ribbon","black","chic","elegant","coquette","parisian","style","gift"] },
    { id: "one-moms-strength", name: "\"One Mom's Strength\"", emoji: "💪", sheet: 3, pos: "3,5",
      category: "mama", meaning: "a mother's quiet strength",
      tags: ["mom","mama","mother","strength","strong","resilience","single mom","powerful","courage"] },
    { id: "violets-pot-dotted", name: "Potted Violets", emoji: "🪻", sheet: 3, pos: "4,1",
      category: "flora", meaning: "a windowsill of violets, home and care",
      tags: ["violet","violets","flower pot","garden","home","grow","blue","grandmother","nurture","bloom"] },
    { id: "blooming-family", name: "\"Blooming Family\" Roses", emoji: "🌹", sheet: 3, pos: "4,2",
      category: "family", meaning: "a family that keeps growing",
      tags: ["family","bloom","roses","grow","growing","together","generations","love","flowers"] },
    { id: "our-sunshine", name: "\"Our Sunshine\" Lemon", emoji: "🌞", sheet: 3, pos: "4,3",
      category: "family", meaning: "the little ray of sunshine in the family",
      tags: ["sunshine","sun","lemon","happy","child","baby","joy","bright","family","our sunshine"] },
    { id: "growing-love", name: "\"Growing Love\" Blueberries", emoji: "🫐", sheet: 3, pos: "4,4",
      category: "family", meaning: "love that grows over time",
      tags: ["love","grow","growing","blueberries","fruit","family","together","nurture","anniversary"] },

    /* ---- Sheet 4 — Hand-Painted Folk --------------------------------- */
    { id: "pink-crab", name: "Pink Crab", emoji: "🦀", sheet: 4, pos: "1,1",
      category: "sea", meaning: "the beach, and the Cancer star sign",
      tags: ["crab","cancer","zodiac","star sign","beach","ocean","sea","summer","shore","pink"] },
    { id: "garden-snail", name: "Garden Snail", emoji: "🐌", sheet: 4, pos: "1,2",
      category: "animal", meaning: "slow down, take your time, patience",
      tags: ["snail","slow","patience","take your time","garden","gentle","calm","mindful","unhurried","nature"] },
    { id: "winged-horse", name: "Winged Horse", emoji: "🐴", sheet: 4, pos: "1,3",
      category: "animal", meaning: "freedom, imagination, taking flight",
      tags: ["horse","pegasus","winged","freedom","imagination","dream","fly","myth","fantasy","escape","wild"] },
    { id: "yellow-wildflowers", name: "Yellow Wildflowers", emoji: "🌼", sheet: 4, pos: "1,4",
      category: "flora", meaning: "a meadow in bloom",
      tags: ["wildflower","flowers","yellow","meadow","field","summer","bloom","nature","cheerful"] },
    { id: "flowers-lemons-oval", name: "Flowers & Lemons", emoji: "🍋", sheet: 4, pos: "1,5",
      category: "flora", meaning: "a sun-drenched garden",
      tags: ["flowers","lemons","garden","citrus","summer","mediterranean","bloom","sunny","fresh"] },
    { id: "strawberry-dotted", name: "Painted Strawberry", emoji: "🍓", sheet: 4, pos: "2,1",
      category: "fruit", meaning: "first love, sweetness, summer days",
      tags: ["strawberry","fruit","sweet","summer","first love","berry","red","picnic","dessert"] },
    { id: "cherries-oval", name: "Twin Cherries", emoji: "🍒", sheet: 4, pos: "2,2",
      category: "fruit", meaning: "two that belong together",
      tags: ["cherry","cherries","pair","couple","sweet","fruit","love","summer","red","twins"] },
    { id: "pink-tulip-blue", name: "Pink Tulip", emoji: "🌷", sheet: 4, pos: "2,3",
      category: "flora", meaning: "spring and gentle affection",
      tags: ["tulip","flower","pink","spring","affection","bloom","graceful","love"] },
    { id: "daisy-field-mustard", name: "Daisy Field", emoji: "🌼", sheet: 4, pos: "2,4",
      category: "flora", meaning: "innocence and sunny fields",
      tags: ["daisy","flowers","field","innocence","summer","yellow","meadow","cheerful","bloom"] },
    { id: "whimsical-fish", name: "Whimsical Fish", emoji: "🐟", sheet: 4, pos: "2,5",
      category: "sea", meaning: "playful, one of a kind, the deep blue",
      tags: ["fish","sea","ocean","quirky","playful","pisces","whimsical","blue","unique","swim"] },
    { id: "daisy-blue-rect", name: "Single Daisy", emoji: "🌼", sheet: 4, pos: "3,1",
      category: "flora", meaning: "he loves me, he loves me not",
      tags: ["daisy","flower","innocence","love","simple","spring","white","bloom"] },
    { id: "red-flower-gold-rect", name: "Red Bloom", emoji: "🌺", sheet: 4, pos: "3,2",
      category: "flora", meaning: "a bold splash of colour",
      tags: ["flower","red","bold","bloom","poppy","bright","cheerful"] },
    { id: "purple-tulip", name: "Purple Tulip", emoji: "🌷", sheet: 4, pos: "3,3",
      category: "flora", meaning: "spring royalty",
      tags: ["tulip","flower","purple","spring","elegant","bloom","graceful"] },
    { id: "dragonfly", name: "Dragonfly", emoji: "🦋", sheet: 4, pos: "3,4",
      category: "animal", meaning: "change, lightness, transformation",
      tags: ["dragonfly","change","transformation","light","summer","pond","nature","renewal","adapt","wings"] },
    { id: "butterfly-cream", name: "Butterfly", emoji: "🦋", sheet: 4, pos: "3,5",
      category: "animal", meaning: "rebirth, metamorphosis, becoming",
      tags: ["butterfly","transformation","rebirth","metamorphosis","change","growth","beauty","spring","wings","new self","freedom"] },
    { id: "red-bow-round", name: "Red Ribbon Bow", emoji: "🎀", sheet: 4, pos: "4,1",
      category: "object", meaning: "a gift given with love",
      tags: ["bow","ribbon","red","gift","present","coquette","sweet","tied"] },
    { id: "strawberry-3d", name: "Ripe Strawberry", emoji: "🍓", sheet: 4, pos: "4,2",
      category: "fruit", meaning: "summer at its sweetest",
      tags: ["strawberry","fruit","sweet","summer","berry","red","ripe","picnic","first love"] },
    { id: "red-flower-tan", name: "Folk Red Flower", emoji: "🌺", sheet: 4, pos: "4,3",
      category: "flora", meaning: "a hand-painted bloom",
      tags: ["flower","red","folk","bloom","painted","bright","cheerful"] },

    /* ---- Sheet 5 — Terracotta & Treasures ---------------------------- */
    { id: "folk-sun-flower-1", name: "Folk Sun Flower", emoji: "🌻", sheet: 5, pos: "1,1",
      category: "folk", meaning: "warmth, the sun, bohemian spirit",
      tags: ["sun","flower","folk","boho","bohemian","warm","terracotta","earthy","radiant","mexican"] },
    { id: "folk-heart-medallion", name: "Folk Heart Medallion", emoji: "❤️", sheet: 5, pos: "1,2",
      category: "love", meaning: "love, handmade and earthy",
      tags: ["heart","love","folk","boho","terracotta","handmade","warm","earthy","devotion"] },
    { id: "folk-wheat-flowers", name: "Folk Wheat & Flowers", emoji: "🌾", sheet: 5, pos: "1,3",
      category: "folk", meaning: "the harvest, the good earth",
      tags: ["wheat","flowers","harvest","folk","earth","autumn","field","rustic","abundance","country"] },
    { id: "folk-green-flower", name: "Folk Green Flower", emoji: "🌿", sheet: 5, pos: "1,4",
      category: "folk", meaning: "a rustic bloom",
      tags: ["flower","green","folk","boho","rustic","earthy","nature","terracotta"] },
    { id: "folk-blue-flower", name: "Folk Blue Flower", emoji: "💠", sheet: 5, pos: "1,5",
      category: "folk", meaning: "a painted folk blossom",
      tags: ["flower","blue","folk","boho","rustic","earthy","terracotta","bloom"] },
    { id: "acoustic-guitar", name: "Acoustic Guitar", emoji: "🎸", sheet: 5, pos: "2,1",
      category: "music", meaning: "music, songs, the road, creativity",
      tags: ["guitar","music","song","sing","band","musician","creative","melody","acoustic","festival","rock","strum"] },
    { id: "crystal-one", name: "Crystal \"1\"", emoji: "1️⃣", sheet: 5, pos: "2,2",
      category: "object", meaning: "number one, first place, the one",
      tags: ["number one","first","winner","number 1","the one","best","champion","sparkle","crystal","anniversary","initial"] },
    { id: "sunflower-round", name: "Sunflower", emoji: "🌻", sheet: 5, pos: "2,3",
      category: "flora", meaning: "happiness that follows the sun",
      tags: ["sunflower","sun","happy","happiness","summer","bright","cheerful","yellow","positivity","bloom"] },
    { id: "radiant-heart", name: "Radiant Heart", emoji: "💛", sheet: 5, pos: "2,4",
      category: "love", meaning: "love that radiates",
      tags: ["heart","love","radiant","gold","sacred heart","warm","glow","devotion","shine"] },
    { id: "folk-flower-round", name: "Folk Flower Medallion", emoji: "🏵️", sheet: 5, pos: "2,5",
      category: "folk", meaning: "an earthy keepsake bloom",
      tags: ["flower","folk","boho","terracotta","rustic","keepsake","earthy"] },
    { id: "marbled-oval", name: "Marbled Sea Stone", emoji: "🌊", sheet: 5, pos: "2,6",
      category: "object", meaning: "the swirl of ocean and earth",
      tags: ["marble","abstract","ocean","sea","earth","stone","blue","green","swirl","nature","calm"] },
    { id: "orange-camera", name: "Retro Camera", emoji: "📷", sheet: 5, pos: "3,1",
      category: "object", meaning: "memories, travel, capturing the moment",
      tags: ["camera","photo","photography","memories","travel","capture","picture","retro","creative","moment","snapshot"] },
    { id: "potted-cactus", name: "Potted Cactus", emoji: "🌵", sheet: 5, pos: "3,2",
      category: "flora", meaning: "resilience, thriving anywhere",
      tags: ["cactus","resilience","desert","tough","survive","southwest","endure","strong","plant","arizona","prickly"] },
    { id: "gold-rose-oval", name: "Engraved Gold Rose", emoji: "🌹", sheet: 5, pos: "3,3",
      category: "love", meaning: "timeless romance",
      tags: ["rose","love","romance","gold","elegant","valentine","anniversary","timeless","flower","devotion"] },
    { id: "smiley-flower", name: "Smiley Flower", emoji: "😊", sheet: 5, pos: "3,4",
      category: "object", meaning: "pure good cheer",
      tags: ["smile","smiley","happy","happiness","cheer","positivity","joy","good vibes","face","fun"] },
    { id: "gold-ladybug", name: "Gold Ladybug", emoji: "🐞", sheet: 5, pos: "3,5",
      category: "luck", meaning: "good luck and small wonders",
      tags: ["ladybug","ladybird","luck","lucky","fortune","nature","garden","gold","beetle","charm"] },
    { id: "initial-frame", name: "Initial Frame", emoji: "🔠", sheet: 5, pos: "3,6",
      category: "object", meaning: "a name, an initial, a personal mark",
      tags: ["initial","letter","monogram","name","frame","personal","keepsake","memory","custom"] },
    { id: "folk-sun-round-1", name: "Terracotta Sunburst", emoji: "☀️", sheet: 5, pos: "4,1",
      category: "folk", meaning: "sunshine, folk warmth",
      tags: ["sun","sunburst","folk","warm","boho","terracotta","radiant","bright","earthy"] },
    { id: "gold-bell", name: "Gold Bell", emoji: "🔔", sheet: 5, pos: "4,2",
      category: "celebration", meaning: "celebration, weddings, good news",
      tags: ["bell","wedding","celebrate","ring","announce","good news","joy","christmas","chime","festive"] },
    { id: "magic-8-ball", name: "Magic 8-Ball", emoji: "🎱", sheet: 5, pos: "4,3",
      category: "object", meaning: "fate, fun, leaving it to chance",
      tags: ["8 ball","eight ball","magic 8 ball","billiards","pool","fate","luck","chance","destiny","game","fun","decision"] },
    { id: "folk-sun-round-2", name: "Folk Sun Medallion", emoji: "☀️", sheet: 5, pos: "4,4",
      category: "folk", meaning: "another little sun",
      tags: ["sun","sunburst","folk","warm","boho","terracotta","radiant","bright","earthy"] },
    { id: "mountain-envelope", name: "Mountain Landscape", emoji: "🏔️", sheet: 5, pos: "4,5",
      category: "object", meaning: "the great outdoors, adventure, the summit",
      tags: ["mountain","mountains","hike","hiking","adventure","outdoors","nature","travel","summit","explore","wilderness","climb"] },
    { id: "confetti-heart", name: "Confetti Heart", emoji: "💛", sheet: 5, pos: "4,6",
      category: "love", meaning: "love worth celebrating",
      tags: ["heart","love","confetti","celebrate","party","gold","joy","anniversary","festive"] }
  ];

  var API = { SHEETS: SHEETS, CHARMS: CHARMS };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = API;
  } else {
    root.CHARM_CATALOG = CHARMS;
    root.CHARM_SHEETS = SHEETS;
  }
})(typeof window !== "undefined" ? window : globalThis);
